# Generated by Django 5.1.5 on 2025-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("last_ping", models.DateTimeField(blank=True, null=True)),
                ("is_online", models.BooleanField(default=False)),
            ],
        ),
    ]
